### ISSUE TITLE
Prediction of probabilities

### ISSUE THREAD

**Issue by studerus** [ramhiser/sparsediscrim#30]
I would like to predict `probabilities` instead of `scores` and `classes`. Is it possible to implement this feature?

**Comment by ramhiser** [comment]
Sorry for my delayed response. Yeah, 'tis a good idea. IIRC `MASS::lda` actually applies the logistic function to the discriminant scores to estimate `probabilities`.

**Comment by ramhiser** [comment]
It turns out `MASS::lda` simply applies Bayes Theorem. I will add posterior probabilities today.

**Comment by ramhiser** [comment]
Classifier checklist:

- [ ] `dlda`
- [ ] `dqda`
- [ ] `sdlda`
- [ ] `sdqda`
- [ ] `smdlda`
- [ ] `smdqda`
- [ ] `lda_pseudo`
- [ ] `lda_schafer`
- [ ] `lda_thomaz`
- [ ] `mdeb`
- [ ] `mdmeb`
- [ ] `mdmp`
- [ ] `hdrda`

**Comment by ramhiser** [comment]
HDRDA already had a calculation for posterior probabilities
